B= input ("print first number  ")
b= int (B)
A= input ("print second number  ")
a= int (A)
s= b + a
m=b-a
u=b* a
k=b**a
d=b/a
md=b//a
print('sum', s, 'difference', m, 'multiplication', u, 'exponentiation' , k, 'degree', d, 'hunky', md, sep='\n')